### ISSUE TITLE
Test Data

### ISSUE THREAD

**Issue by dreammxy** [wouterpeyrot/CCGWAS#1]
Hi Wouter!
Thanks for your work!
 I tried your upload test data, but it cannot work, and so are the output files. Additionally, I would like to make sure in your  script"**K_B1B0_high = 0.005 , K_B1B0_low = 0.02**" and "N_A1 = 40675 , **N_B1 = 4819** , N_A0 = 20352 , **N_B0 = 31358** , **N_overlap_A0B0 = 24265**". 
Thanks a lot!

Maggie

**Comment by wouterpeyrot** [comment]
Hi Maggie,

 

Thank you for catching these typos! I adjusted the numbers accordingly, also see below.

 

Still I think these typos shouldn’t make CC-GWAS crash: what error message do you get? Did you install all relevant R packages (see “Getting started”)?

 

Let me know how you go!

 

Thanks Wouter

 

CCGWAS( outcome_file = "test.out" , A_name = "SCZ" , B_name = "BIP" , 

        sumstats_fileA1A0 = "./test.casecontrol.gwas.SCZ.10snps.txt.gz" ,

        sumstats_fileB1B0 = "./test.casecontrol.gwas.BIP.10snps.txt.gz" ,

        K_A1A0 = 0.004 , K_A1A0_high = 0.01 , K_A1A0_low = 0.004 ,  

        K_B1B0 = 0.01 , K_B1B0_high = 0.02 , K_B1B0_low = 0.005 , 

        h2l_A1A0 = 0.2 , h2l_B1B0 = 0.20 , rg_A1A0_B1B0 = 0.70 , intercept_A1A0_B1B0 = 0.2425 , m = 1e4 ,  

        N_A1 = 40675 , N_B1 = 20352 , N_A0 = 64643 , N_B0 = 31358 , N_overlap_A0B0 = 24265 )

 

 

 

From: dreammxy ***@***.***>
Reply to: wouterpeyrot/CCGWAS ***@***.***>
Date: Thursday, 25 March 2021 at 4:17 
To: wouterpeyrot/CCGWAS ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [wouterpeyrot/CCGWAS] Test Data (#1)

 

Hi Wouter!
Thanks for your work!
I tried your upload test data, but it cannot work, and so are the output files. Additionally, I would like to make sure in your script"K_B1B0_high = 0.005 , K_B1B0_low = 0.02" and "N_A1 = 40675 , N_B1 = 4819 , N_A0 = 20352 , N_B0 = 31358 , N_overlap_A0B0 = 24265".
Thanks a lot!

Maggie

**Comment by dreammxy** [comment]
Hi, Wouter!
Thank you very much for your quick reply. I found the problem. When I download the test data  through "save as a file", it is 131KB, and it cannot gunzip. I downlod though "download" button, and the data is fine. I have done with your test data. Thanks again!
