### ISSUE TITLE
prevalence of the disorder in the elderly population or the prevalence in the population in general

### ISSUE THREAD

**Issue by nenduru1** [wouterpeyrot/CCGWAS#11]
Hello,

I have a question related to the prevalence rate.
In the case of diseases where prevalent rate varies by age, like for stroke, AD and other diseases, would you suggest to use the prevalence of the disorder in the elderly population or the prevalence in the population in general?

thank you.

**Comment by wouterpeyrot** [comment]
I suggest to use the average prevalence of the population you are analysing. In addition, you can specify an high and a low range of the prevalence value.

**Comment by nenduru1** [comment]
thank you.
