### ISSUE TITLE
ccGWAS for continuous traits

### ISSUE THREAD

**Issue by ferfacal92** [wouterpeyrot/CCGWAS#13]
Hello!
I wonder if I can use ccGWAS for association testing between a dichotomous trait (for example, diabetes mellitus vs controls) and a continuos one (for example, body mass index).

Thank you in advance,
Fernando

**Comment by wouterpeyrot** [comment]
Hi Fernando, no this is not possible (CC-GWAS compares the allele frequencies across two groups of cases), unless you want to dichotomous BMI so this also gets case group (e.g. obesity)

**Comment by ferfacal92** [comment]
Thak you for your answer!

Fernando
________________________________
De: Wouter Peyrot ***@***.***>
Enviado: jueves, 20 de julio de 2023 10:20
Para: wouterpeyrot/CCGWAS ***@***.***>
Cc: ferfacal92 ***@***.***>; Author ***@***.***>
Asunto: Re: [wouterpeyrot/CCGWAS] ccGWAS for continuous traits (Issue #13)


Hi Fernando, no this is not possible (CC-GWAS compares the allele frequencies across two groups of cases), unless you want to dichotomous BMI so this also gets case group (e.g. obesity)
