### ISSUE TITLE
Trans-ancestry 

### ISSUE THREAD

**Issue by dreammxy** [wouterpeyrot/CCGWAS#3]
Hi, Wouter!
Thank you for your excellent work! Is CC-GWAS suitable for the trans-ancestry populations of different disorders?

Best wishes!

Maggie

**Comment by wouterpeyrot** [comment]
Hi Maggie, thank you for your question. CC-GWAS is intended for within-ancestry analyses, and not suitable for trans-ancestry analyses. I agree this would be an interesting direction for future research. Best wishes, Wouter
