### ISSUE TITLE
Error in plot.window(...) : se necesitan valores finitos de 'xlim' Además: Warning messages: 1: In sqrt(hoAhoAm * hoBhoBm) : Se han producido NaNs 2: In sqrt(Fst$Fst_A1A0) : Se han producido NaNs 3: In sqrt(Fst$Fst_A1A0) : Se han producido NaNs

### ISSUE THREAD

**Issue by corunesa** [wouterpeyrot/CCGWAS#4]
Hello to all of you!
I'm trying to perform the CC-GWAS but I get an error and I don't know why. Can anyone help me?
Thank you very much in advance!

Plot of F_ST,causal (see paper for details) saved to (...)
Error in plot.window(...) : se necesitan valores finitos de 'xlim'
Además: Warning messages:
1: In sqrt(hoAhoAm * hoBhoBm) : Se han producido NaNs
2: In sqrt(Fst$Fst_A1A0) : Se han producido NaNs
3: In sqrt(Fst$Fst_A1A0) : Se han producido NaNs

And the .log:

No information found of A1B1 comparison, CC-GWAS will be based on A1A0 and B1B0. Reading data...

Read data of 6,807,966 SNPs for A1A0 from (...), of these...
...0 SNPs were deleted based on missing value in at least one column (0%)
...0 SNPs were deleted based on MAF<=0.01
...0 SNPs were deleted with Neff < 2/3 of max(Neff)
...0 duplicate SNPs were deleted 
...maximum OR = 1.72, minimum OR = 0.55
...0 SNPs were deleted based on OR>2 or OR<0.5
...SE is available, z-values based on log(OR)/SE
...transposing ORs to observed scale betas (this may take some time)...
...cor(beta_viaNeff,beta_viaOR) = 0.9878 (SHOULD BE CLOSE TO 1)
...mean(beta_viaNeff/beta_viaOR) = 1 for non-null SNPs with OR<0.99 | OR>1.01 (SHOULD BE CLOSE TO 1)
...resulting in 6,807,966 SNPs for A1A0

Read data of 8,177,649 SNPs for B1B0 from (...), of these...
...0 SNPs were deleted based on missing value in at least one column (0%)
...0 SNPs were deleted based on MAF<=0.01
...0 SNPs were deleted with Neff < 2/3 of max(Neff)
...0 duplicate SNPs were deleted 
...maximum OR = 2.84, minimum OR = 0.37
...127 SNPs were deleted based on OR>2 or OR<0.5
...SE is available, z-values based on log(OR)/SE
...transposing ORs to observed scale betas (this may take some time)...
...cor(beta_viaNeff,beta_viaOR) = 0.9864 (SHOULD BE CLOSE TO 1)
...mean(beta_viaNeff/beta_viaOR) = 1 for non-null SNPs with OR<0.99 | OR>1.01 (SHOULD BE CLOSE TO 1)
...resulting in 8,177,522 SNPs for B1B0

Merging data based on SNP-names, yielding...
...6,721,881 overlapping SNPs across A1A0 & B1B0
...29 SNPs were deleted based on discordant CHR or BP position
...0 SNPs were deleted based on difference in allele names
...alligned reference alleles (changed reference allele in B1B0 to match A1A0 for 0 SNPs)
...Deleted all 1,038,476 strand ambiguous SNPs, leaving 5,683,376 SNPs for analyses

Of these overlapping SNPs... (this overview can help to double-check input)
...the mean OR in A1A0 equals 1.00214 (should be very close to 1)
...the mean OR in B1B0 equals 1.00229 (should be very close to 1)
...9 are signifacntly associated with A1A0 at p<5e-8
...0 are signifacntly associated with B1B0 at p<5e-8
...the mean allele frequency in A1A0 equals 0.46292
...the mean allele frequency in B1B0 equals 0.46261
...the correlation between the allele frequencies in A1A0 and B1B0 is 0.99903 (should be very close to 1, i.e. > 0.98)

Plot of F_ST,causal (see paper for details) saved to (...)

**Comment by wouterpeyrot** [comment]
Thank you for your message, corunesa. Can you copy-paste your CC-GWAS input command here for me to see what may be going on?

**Comment by corunesa** [comment]
Sure!

path_analysis<-"/Users/elena/Trabajo/SynologyDrive/GENETICA/analisis/"

CCGWAS( outcome_file = paste0(path_analysis,"CMB_SVO.out"), A_name = "CMB" , B_name = "SVO" , 
        sumstats_fileA1A0 = paste0(path_analysis,"CMB_ccgwas_format_clean.txt") ,
        sumstats_fileB1B0 = paste0("/Users/elena/Trabajo/SynologyDrive/GENETICA/analisis/MEGASTROKE_SVS_EUR_ccgwas_format_clean.txt") ,
        K_A1A0 = 0.065 , K_A1A0_high = 0.65 , K_A1A0_low = 0.0065 ,  
        K_B1B0 = 0.0011 , K_B1B0_high = 0.011 , K_B1B0_low = 0.00011 , 
        h2l_A1A0 = -0.0152 , h2l_B1B0 = 0.0042 , rg_A1A0_B1B0 = 0.207167578600455 , intercept_A1A0_B1B0 = 0.0212 , m = 5e3 ,  
        N_A1 = 3556 , N_B1 = 5386 , N_A0 = 25862 , N_B0 = 11710 , N_overlap_A0B0 = 0,
        subtype_data = T)

Thank you very much!!



Elena Muiño Acuña
Neurología
Stroke Pharmacogenomics and Genetics
Fundació Institut de Recerca de l`Hospital de la Santa Creu i Sant Pau
Equipo CADASIL, www.cadasil.es <http://www.cadasil.es/>
***@***.*** ***@***.***>

**Comment by corunesa** [comment]
Sure!

path_analysis<-"..."

CCGWAS( outcome_file = paste0(path_analysis,"ccgwas_1_2.out"), A_name = "phenotype_1" , B_name = "phenotype_2" , 
        sumstats_fileA1A0 = paste0(path_analysis,"phenotype_1_ccgwas_format_clean.txt") ,
        sumstats_fileB1B0 = paste0("phenotype_2_ccgwas_format_clean.txt") ,
        K_A1A0 = 0.065 , K_A1A0_high = 0.65 , K_A1A0_low = 0.0065 ,  
        K_B1B0 = 0.0011 , K_B1B0_high = 0.011 , K_B1B0_low = 0.00011 , 
        h2l_A1A0 = -0.0152 , h2l_B1B0 = 0.0042 , rg_A1A0_B1B0 = 0.207167578600455 , intercept_A1A0_B1B0 = 0.0212 , m = 5e3 ,  
        N_A1 = 3556 , N_B1 = 5386 , N_A0 = 25862 , N_B0 = 11710 , N_overlap_A0B0 = 0,
        subtype_data = T)

Thank you very much!!

**Comment by wouterpeyrot** [comment]
Thanks, the negative heritability estimate (h2l_A1A0 = -0.0152) is the problem. And I note that the other heritability is also very small (h2l_B1B0 = 0.0042). One solution can be to use more sensible heritability estimates from the literature, or to double-check if your heritability estimates are correct. When your heritability estimates are correct this suggest you have very low polygenic signal in your data, which, unfortunately, will give you a small chance to find reliable case-case loci.
