### ISSUE TITLE
Hi,I came across an error when running the CCGWAS.I would be appriciated if you could give me some advice.

### ISSUE THREAD

**Issue by Nightchanger1** [wouterpeyrot/CCGWAS#6]
...0 SNPs were deleted based on difference in allele names 
...alligned reference alleles (changed reference allele in B1B0 to match A1A0 for 0 SNPs) 
...Deleted all 0 strand ambiguous SNPs, leaving 0 SNPs for analyses 
 
Of these overlapping SNPs... (this overview can help to double-check input) 
...the mean OR in A1A0 equals NaN (should be very close to 1) 
...the mean OR in B1B0 equals NaN (should be very close to 1) 
...0 are signifacntly associated with A1A0 at p<5e-8 
...0 are signifacntly associated with B1B0 at p<5e-8 
...the mean allele frequency in A1A0 equals NaN 
...the mean allele frequency in B1B0 equals NaN 
...the correlation between the allele frequencies in A1A0 and B1B0 is NA (should be very close to 1, i.e. > 0.98) 
 
Plot of F_ST,causal (see paper for details) saved to BIPMDD.out.Fst.pdf 
 
Results may suffer from type I error when the bivariate LDSC intercept would be inflated due to other causes than covariance of error terms 
...therefore, take the minumum of the analytically expected and LDSC estimated value 
...LDSC estimated value = 0 
...Analytically expected = 0 (based on confirmed N_overlap_A0B0 = 0) 
...Thus, covariance of error terms is modelled based on an intercept of 0 
Error in if (OLS2["intercept"] == 0) { :

**Comment by wouterpeyrot** [comment]
Apologies for the delay. Was this issue resolved? If not, could you send me your input for CCGWAS and the thirst couple of lines of your input sumstats?
