### ISSUE TITLE
Lacking of frequency of the EA in controls in input GWAS summary data

### ISSUE THREAD

**Issue by zongchangli** [wouterpeyrot/CCGWAS#7]
Hi, I am trying to replicate some of CCGWAS paper findings with PGC GWAS summary datat. I noticed that CC-GWAS requires the 
FRQ (the frequency of the EA in controls) information in the input data, but for some PGC GWAS summary data(eg. ASD, ASHD), the FRQ information is missing. I want to know that how to address this issue? Thanks

**Comment by wouterpeyrot** [comment]
In this case, we advice to use the allele frequency in the reference sample that was used for imputation.
