### ISSUE TITLE
CC-GWAS is being aborted

### ISSUE THREAD

**Issue by zhangcc89claire** [wouterpeyrot/CCGWAS#8]
Hi,

I encountered an issue while executing CC-gWAS. Could you please assist me?

> CC-GWAS is being aborted, because mean(beta_viaNeff/beta_viaOR) = 0.8864 < 0.9 risking inflated type I error at stress test SNPs. Please contact wpeyrot@hsph.harvard.edu to resolve this issue.

Thanks!
Cheng

**Comment by wouterpeyrot** [comment]
Hi Cheng,

Thank you for reaching out. Did you see this issue? https://github.com/wouterpeyrot/CCGWAS/issues/2 
Let me know if this does not help to solve your issue.

Best Wouter
