### ISSUE TITLE
Error in if (OLS2["intercept"] == 0)

### ISSUE THREAD

**Issue by nenduru1** [wouterpeyrot/CCGWAS#9]
Hi I have similar issue related to #6 . please see my input parameters

CCGWAS( outcome_file = "BIP_MDD.out" , A_name = "MDD", B_name = "BIP",
        sumstats_fileA1A0 = "C:/Users/nenduru/Downloads/CCGWAS/data/BIP.ccgwas.1ksnps.txt",
        sumstats_fileB1B0 = "C:/Users/nenduru/Downloads/CCGWAS/data/MDD.ccgwas.1ksnps.txt",
        K_A1A0 = 0.004 , K_A1A0_high = 0.01 , K_A1A0_low = 0.004 ,  
        K_B1B0 = 0.01 , K_B1B0_high = 0.02 , K_B1B0_low = 0.005 , 
        h2l_A1A0 = 0.2 , h2l_B1B0 = 0.20 , rg_A1A0_B1B0 = 0.70 , intercept_A1A0_B1B0 = 0.2425 , m = 0 ,  
        N_A1 = 40675 , N_B1 = 20352 , N_A0 = 64643 , N_B0 = 31358 , N_overlap_A0B0 = 0 )

thank you.

**Comment by wouterpeyrot** [comment]
Can you check in sumstats_fileA1A0 and sumstats_fileB1B0  that the column names are exactly as below and in that order? 
"Column names should be: SNP, CHR, BP, EA, NEA, FRQ, OR, SE, P, Neff."

**Comment by nenduru1** [comment]
thank you for the quick response. I was able to overcome this error after modifying the parameters (previously m=0 changed to m=1000) .
